/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as GameRouteImport } from './routes/game'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PlayComputerRouteImport } from './routes/play.computer'
import { Route as PlayLocalRouteImport } from './routes/play.local'
import { Route as ReviewIdRouteImport } from './routes/review.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayComputerRoute = PlayComputerRouteImport.update({
  id: '/play/computer',
  path: '/play/computer',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayLocalRoute = PlayLocalRouteImport.update({
  id: '/play/local',
  path: '/play/local',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIdRoute = ReviewIdRouteImport.update({
  id: '/review/$id',
  path: '/review/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/game': typeof GameRoute
  '/history': typeof HistoryRoute
  '/premium': typeof PremiumRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/play/computer': typeof PlayComputerRoute
  '/play/local': typeof PlayLocalRoute
  '/review/$id': typeof ReviewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/game': typeof GameRoute
  '/history': typeof HistoryRoute
  '/premium': typeof PremiumRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/play/computer': typeof PlayComputerRoute
  '/play/local': typeof PlayLocalRoute
  '/review/$id': typeof ReviewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/game': typeof GameRoute
  '/history': typeof HistoryRoute
  '/premium': typeof PremiumRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/play/computer': typeof PlayComputerRoute
  '/play/local': typeof PlayLocalRoute
  '/review/$id': typeof ReviewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/game'
    | '/history'
    | '/premium'
    | '/progress'
    | '/settings'
    | '/play/computer'
    | '/play/local'
    | '/review/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/game'
    | '/history'
    | '/premium'
    | '/progress'
    | '/settings'
    | '/play/computer'
    | '/play/local'
    | '/review/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/game'
    | '/history'
    | '/premium'
    | '/progress'
    | '/settings'
    | '/play/computer'
    | '/play/local'
    | '/review/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  GameRoute: typeof GameRoute
  HistoryRoute: typeof HistoryRoute
  PremiumRoute: typeof PremiumRoute
  ProgressRoute: typeof ProgressRoute
  SettingsRoute: typeof SettingsRoute
  PlayComputerRoute: typeof PlayComputerRoute
  PlayLocalRoute: typeof PlayLocalRoute
  ReviewIdRoute: typeof ReviewIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/computer': {
      id: '/play/computer'
      path: '/play/computer'
      fullPath: '/play/computer'
      preLoaderRoute: typeof PlayComputerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/local': {
      id: '/play/local'
      path: '/play/local'
      fullPath: '/play/local'
      preLoaderRoute: typeof PlayLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$id': {
      id: '/review/$id'
      path: '/review/$id'
      fullPath: '/review/$id'
      preLoaderRoute: typeof ReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  GameRoute: GameRoute,
  HistoryRoute: HistoryRoute,
  PremiumRoute: PremiumRoute,
  ProgressRoute: ProgressRoute,
  SettingsRoute: SettingsRoute,
  PlayComputerRoute: PlayComputerRoute,
  PlayLocalRoute: PlayLocalRoute,
  ReviewIdRoute: ReviewIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
